// client/src/components/Contact.jsx
import '../styles/contact.css'
function Contact(){
    return(
        <div className="contact">
            <h1>Contact us</h1>
            <p><a href="mailto:skrsumit250@gmail.com">skrsumit250@gmail.com</a></p>
            <p>+91-1234567890</p>
            <p>Building X Sector Y, Hyderabad, India</p>
            <hr />

            <h1>Follow Us</h1>
            <p><a href="">Linkdin</a></p>
            <p><a href="">Instagram</a></p>
            <p><a href="">Facebook</a></p>
            <p><a href="">Twitter</a></p>
        </div>
    )
}
export default Contact;

// client/src/app/components/contact/contact.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-contact',
  imports: [],
  templateUrl: './contact.component.html',
  styleUrl: './contact.component.css'
})
export class ContactComponent {
  mail:string = 'skrsumit250@gmail.co'
}

<div class="contact">
    <h1>Contact us</h1>
    <p><a href="mailto:skrsumit250@gmail.com">{{mail}}</a></p>
    <p>+91-1234567890</p>
    <p>Building X Sector Y, Hyderabad, India</p>
    <hr />

    <h1>Follow Us</h1>
    <p><a href="">Linkdin</a></p>
    <p><a href="">Instagram</a></p>
    <p><a href="">Facebook</a></p>
    <p><a href="">Twitter</a></p>
</div>
