// client/src/components/Card.jsx
import '../styles/card.css'
import {Link} from 'react-router-dom'
function Card(props){
    const { _id,company, role, experience, location,skills ,description,imgURL} = props.data;

    return(
        <div className="card">
            <img src={imgURL} alt="" />
            <div className="details">
                <li>{company} | {role}</li>
                <li>Experince: {experience} | location: {location}</li>
                <li>Skills Required : {skills}</li>
                <li>{description}</li>
                <button><Link to={`/Apply/${_id}`}>Apply</Link></button>
            </div>
        </div>
    )
}
export default Card;

// client/src/app/components/card/card.component.ts
import { Component, Input} from '@angular/core';
import { RouterLink, RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-card',
  imports: [],
  templateUrl: './card.component.html',
  styleUrl: './card.component.css'
})
export class CardComponent {
  @Input() data: any;
}

<div class="card">
    <img [src]='data.imgURL' alt="" />
    <div class="details">
        <li>{{data.company}} | {{data.role}}</li>
        <li>Experince: {{data.experience}} | location: {{data.location}}</li>
        <li>Skills Required : {{data.skills}}</li>
        <li>{{data.description}}</li>
        <!-- <button><Link to={`/Apply/${_id}`}>Apply</Link></button> -->
        <button><a>Apply</a></button>
    </div>
</div>
