// client/src/app/components/footer/footer.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-footer',
  imports: [RouterLink, RouterOutlet],
  templateUrl: './footer.component.html',
  styleUrl: './footer.component.css'
})
export class FooterComponent {

}

<div class="footer">
    <ul>
        <hr />
        <li>Privacy Policy</li>
        <li>Terms of use</li>
        <li>Refund Policy</li>
        <p>© 2024 <a routerLink="https://skrsumit250.github.io/Portfolio/">Sumit Kumar</a> All rights reserved</p>
        <hr />
    </ul>
</div>

// client/src/components/Footer.jsx
import '../styles/footer.css'
function Footer(){
    return(
        <div className="footer">
            <ul>
                <hr />
                <li>Privacy Policy</li>
                <li>Terms of use</li>
                <li>Refund Policy</li>
                <p>© 2024 <a href="https://skrsumit250.github.io/Portfolio/">Sumit Kumar</a> All rights reserved</p>
                <hr />
            </ul>
            
        </div>
    )
}
export default Footer;
