// client/src/components/Navbar.jsx
import '../styles/navbar.css'
import {Link} from 'react-router-dom'
function Navbar(){
    return(
        <div className="navbar">
            <h1>Job.Search( )</h1>
            <ul className='nav-links'>
                <li><Link to="/">Home</Link></li>
                <li><Link to="/Jobs">Find Jobs</Link></li>
                <li><Link to="/Post_Jobs">Post Jobs</Link></li>
                <li><Link to="/Contact">Contact Us</Link></li>
            </ul>
        </div>
    )
}
export default Navbar;

// client/src/app/components/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-navbar',
  imports:  [RouterLink],
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.css'
})
export class NavbarComponent {

}

<div class="navbar">
    <h1>Job.Search( )</h1>
    <ul class='nav-links'>
        <li><a routerLink="">Home</a></li>
        <li><a routerLink="Jobs">Find Jobs</a></li>
        <li><a routerLink="Post_Jobs">Post Jobs</a></li>
        <li><a routerLink="Contact">Contact Us</a></li>
    </ul>
</div>
